### ISSUE TITLE
Link did not work for Andrea and i this morning when i tried to do a demo

### ISSUE THREAD

**Issue by cathymoran** [OvilleTown/CovidAssessmentsIssues#6] opened 2020-11-19 18:33 UTC
Also - we decided to just go with employees for now
When the employee answers 'yes' to a question - the end result page should say ' Do not enter the workplace. Please complete the online Public Health self-assessment here( link)  and follow instructions. Contact your supervisor or manager.'
The 'yes' questionnaires can go to HR Inbox.

**Comment by OvilleTown** [comment] 2020-11-23 03:00
part about results page a duplicate of #5.

**Comment by OvilleTown** [comment] 2020-11-23 03:02
The link requires VPN to work, as well it requires https in the testing environment making it https://assessments.orangeville.ca

**Closed by OvilleTown** 2020-11-23 03:02 UTC
Labels: duplicate, help wanted
